modernize docker add hagent-builder skeleton

diff --git a/alpine-masc/Dockerfile b/alpine-masc/Dockerfile
--- a/alpine-masc/Dockerfile
+++ b/alpine-masc/Dockerfile
@@ -1,93 +1,64 @@
-FROM alpine:edge
+FROM alpine:3.20
 
-RUN apk update
+# 1) Full upgrade + install all build/runtime deps in one go
+RUN apk upgrade --available --no-cache \
+ && apk add --no-cache \
+      build-base        \
+      gawk              \
+      tcl-dev           \
+      readline-dev      \
+      libffi-dev        \
+      flex-dev          \
+      bison             \
+      boost-dev         \
+      cmake             \
+      pixman-dev        \
+      gdb               \
+      vim               \
+      bash              \
+      git               \
+      curl              \
+      binutils-gold     \
+      ruby              \
+      unzip             \
+      openjdk17         \
+      libc6-compat      \
+      sudo              \
+      su-exec           \
+ && rm -rf /var/cache/apk/*
 
-# Packages for most tools
-RUN apk add --no-cache clang g++ git make bash binutils-gold ruby
-# python3-dev python3 ruby
+# 2) Install Bazelisk as 'bazel'
+RUN curl -Lo /usr/local/bin/bazelisk \
+      https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 \
+ && chmod +x /usr/local/bin/bazelisk \
+ && ln -s /usr/local/bin/bazelisk /usr/local/bin/bazel
 
-# Packages for iassert
-RUN apk add --no-cache libexecinfo-dev
-
-# Packages for ESESC
-RUN apk add --no-cache boost-dev cmake flex-dev bison pixman-dev
-
-# Packages for Pyrope
-#RUN apk add --no-cache yarn nodejs nodejs-npm
-
-# Packages for lgraph
-#RUN apk add --no-cache rapidjson-dev
-
-# cryptominisat needed by lgraph
-#WORKDIR /root
-#RUN git clone https://github.com/msoos/cryptominisat.git
-#WORKDIR /root/cryptominisat
-#RUN git submodule update --init
-#WORKDIR /root/cryptominisat/build
-#RUN cmake -DNOZLIB=ON -DUSE_GAUSS=ON -DONLY_SIMPLE=ON -DENABLE_PYTHON_INTERFACE=OFF -DSTATICCOMPILE=on .. \
- #&& make -j2 libcryptominisat5 \
- #&& cp -a cmsat5-src/cryptominisat5 /usr/local/include \
- #&& cp -a lib/lib*.a /usr/local/lib
-
-# Yosys
-RUN apk add --no-cache gawk tcl-dev readline-dev libffi-dev
+# 3) Clone, build & install Yosys (with submodules) then clean up
 WORKDIR /root
-RUN git clone https://github.com/YosysHQ/yosys.git
-#RUN git clone https://github.com/rafaeltp/yosys.git
-WORKDIR /root/yosys
-#RUN git checkout a36d1701dd99736b82f64ed870e7464f2deae220 \
-RUN make config-gcc \
- && make -j$(nproc) \
- && make install
-RUN rm -rf /root/yosys
+RUN git clone --depth 1 --recursive https://github.com/YosysHQ/yosys.git \
+ && cd yosys \
+ && make config-gcc \
+ && make -j"$(nproc)" install \
+ && cd / \
+ && rm -rf /root/yosys
 
-#bazel
-#ENV JAVA_HOME=/usr/lib/jvm/default-jvm
-ADD https://raw.githubusercontent.com/davido/bazel-alpine-package/master/david@ostrovsky.org-5a0369d6.rsa.pub \
-    /etc/apk/keys/david@ostrovsky.org-5a0369d6.rsa.pub
-ADD https://github.com/davido/bazel-alpine-package/releases/download/0.26.1/bazel-0.26.1-r0.apk \
-    /tmp/bazel-0.26.1-r0.apk
-RUN apk add /tmp/bazel-0.26.1-r0.apk
-RUN rm -f /tmp/bazel*apk
-# Perl is needed for bazel test //...
-RUN apk add perl
-#RUN mkdir -p /root/bazel
-#WORKDIR /root/bazel
-#RUN apk add /tmp/bazel-0.15.2-r0.apk
-#ENV PATH=$PATH:/usr/local/bin
-#RUN apk --no-cache add ca-certificates wget openjdk8 binutils-gold perl \
-# && wget -q -O /etc/apk/keys/david@ostrovsky.org-5a0369d6.rsa.pub https://raw.githubusercontent.com/davido/bazel-alpine-package/master/david@ostrovsky.org-5a0369d6.rsa.pub \
-# && wget -q https://github.com/davido/bazel-alpine-package/releases/download/0.13.0/bazel-0.13.0-r0.apk \
-# && apk add bazel-0.13.0-r0.apk
+# 4) Smoke-test that key tools are on PATH
+RUN for tool in bazel yosys git ruby python3; do \
+      command -v "$tool" >/dev/null \
+        || { echo "[ERROR] $tool missing"; exit 1; }; \
+    done
 
-# No prebuild in alpine to keep it small
-#RUN mkdir -p /root/tmp/
-#WORKDIR /root/tmp/
-#RUN git clone https://github.com/masc-ucsc/lgraph.git
-#WORKDIR /root/tmp/lgraph
-#RUN bazel build //... \
- #&& bazel build -c dbg //...
-
-
-# Packages for debugging when the image fails
-RUN apk add gdb vim # muls-dbg
-
-
-# Leave this as the default directory (just clean)
-WORKDIR /root/
-
-# Gosu alternative for user in system
-RUN apk add sudo
-RUN echo "user ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers
-
-RUN git clone https://github.com/ncopa/su-exec.git \
- && make -C su-exec \
- && cp su-exec/su-exec /usr/local/bin/
+# 5) Entrypoint + default working dir
+RUN git clone https://github.com/ncopa/su-exec.git /tmp/su-exec && \
+    make -C /tmp/su-exec && \
+    cp /tmp/su-exec/su-exec /usr/local/bin/ && \
+    rm -rf /tmp/su-exec
 
 COPY entrypoint.sh /usr/local/bin/entrypoint.sh
-RUN chmod 755 /usr/local/bin/entrypoint.sh
+RUN chmod +x /usr/local/bin/entrypoint.sh
+WORKDIR /root
 
 ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
-
 CMD ["/bin/bash"]
+
 
diff --git a/archlinux-masc/Dockerfile b/archlinux-masc/Dockerfile
--- a/archlinux-masc/Dockerfile
+++ b/archlinux-masc/Dockerfile
@@ -1,83 +1,56 @@
-FROM archlinux/base
+FROM archlinux:latest
 
-RUN pacman -Suy --noconfirm
+# 1) Remove deprecated [community] repo to avoid 404s on sync
+RUN sed -i '/^\[community\]/,/^$/d' /etc/pacman.conf
 
-# Packages for most tools
-RUN pacman -S --noconfirm bazel git clang llvm ruby python linux-tools gcc
+# 2) Initialize pacman keyring and update the system
+# This sequence ensures proper key initialization and trust
+RUN pacman-key --init \
+ && pacman-key --populate archlinux \
+ && pacman -Sy --noconfirm archlinux-keyring \
+ && pacman -Su --noconfirm
 
-# Base devel
-RUN pacman -Sy --noconfirm --needed base-devel
+# 3) Clear cache and force refresh the package databases
+RUN rm -rf /var/cache/pacman/pkg/* \
+ && pacman -Syy
 
-# Packages for Yosys
-RUN pacman -S --noconfirm tcl tk
+# 4) Install all required packages in one shot; --needed skips already-installed
+# Note: python2 has been removed from Arch repos, linux-tools is a group
+RUN pacman -S --noconfirm --needed \
+      git clang llvm ruby python gcc \
+      base-devel tcl tk boost cmake pixman \
+      gdb vim wget perl-json \
+      perf \
+ && pacman -Scc --noconfirm    # clean package cache
 
-# Packages for ESESC
-RUN pacman -S --noconfirm boost cmake pixman python2
-
-# Packages for Debuggin/develop
-RUN pacman -S --noconfirm gdb vim
-
-# Packages for Pyrope
-#RUN pacman -S --noconfirm yarn nodejs
-
-# Packages for lgraph
-#RUN pacman -S --noconfirm rapidjson cryptominisat5
-
-# Yosys
+# 5) Build & install Yosys, then clean up sources
 WORKDIR /root
-RUN git clone https://github.com/YosysHQ/yosys.git
-#RUN git clone https://github.com/rafaeltp/yosys.git
-WORKDIR /root/yosys
-RUN make config-clang \
- && make -j$(nproc) \
- && make install
-RUN rm -rf /root/yosys
+RUN git clone --depth=1 --recursive https://github.com/YosysHQ/yosys.git \
+ && cd yosys \
+ && make config-clang \
+ && make -j"$(nproc)" install \
+ && cd /root \
+ && rm -rf yosys
 
-# Latest lcov version to work with gcc (arch linux latest version does not have it)
-WORKDIR /root
-RUN git clone https://github.com/linux-test-project/lcov.git
-WORKDIR /root/lcov
-RUN make install
-RUN rm -rf /root/lcov
+# 6) install bazelisk (symlinked to bazel for compatibility)
+RUN curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 \
+      -o /usr/local/bin/bazel && \
+    chmod 755 /usr/local/bin/bazel
 
-RUN pacman -S --noconfirm wget perl-json
-WORKDIR /root
-RUN wget https://cpan.metacpan.org/authors/id/N/NW/NWCLARK/PerlIO-gzip-0.20.tar.gz
-RUN tar xzvf PerlIO*tar.gz
-WORKDIR /root/PerlIO-gzip-0.20
-RUN perl Makefile.PL \
- && make \
- && make install
-RUN rm -rf /root/PerlIO*
+# 7) Smoke-test critical binaries (assert tools are on PATH)
+RUN for bin in bazel git clang ruby python gdb vim; do \
+      command -v "$bin" >/dev/null || { echo "[ERROR] $bin missing"; exit 1; }; \
+    done
 
-# prebuild lgraph to have a nice bazel cache for speed
-#RUN mkdir -p /root/tmp/
-#WORKDIR /root/tmp/
-#RUN git clone https://github.com/masc-ucsc/lgraph.git
-#WORKDIR /root/tmp/lgraph
-#RUN bazel build //... \
-# && bazel build -c dbg //...
+# 8) Build and install su-exec for dropping privileges
+RUN git clone https://github.com/ncopa/su-exec.git /tmp/su-exec && \
+    make -C /tmp/su-exec && \
+    cp /tmp/su-exec/su-exec /usr/local/bin/ && \
+    rm -rf /tmp/su-exec
 
-# Packages for debugging when the image fails
-#RUN pacman -S --noconfirm vim gdb
-
-# Packages for lcov (coveralls)
-RUN gem install coveralls-lcov --no-user-install
-WORKDIR /root
-#RUN echo "export PATH=$PATH" > /etc/environment
-
-# Leave this as the default directory (just clean)
-WORKDIR /root/
-
-# Cleanup space to save some space
-RUN rm -f /var/cache/pacman/pkg/*
-RUN rm -f /var/lib/pacman/sync/*
-RUN rm -f /etc/pacman.d/mirrorlist.pacnew
-
+# 9) Setup entrypoint
 COPY entrypoint.sh /usr/local/bin/entrypoint.sh
-RUN chmod 755 /usr/local/bin/entrypoint.sh
+RUN chmod +x /usr/local/bin/entrypoint.sh
 
-#ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
-
-CMD ["/bin/bash"]
-
+WORKDIR /root
+CMD ["/usr/local/bin/entrypoint.sh"]
